voxpupuli/puppet-lldpd

- metadata.json
> set correct versions for OSes in metadata.json

- metadata.json
> bump lower puppet-systemd version to at least 1.0.0

- metadata.json
> drop fedora 24, add fedora 26/27

- .fixtures.yml
- manifests/repo.pp
- manifests/service.pp
- spec/classes/lldpd_spec.rb
- spec/spec_helper.rb
> Add unit tests + minor bugfixes

- data/Archlinux.yaml
- data/CentOS-6.yaml
- data/CentOS-7.yaml
- data/CentOS.yaml
- data/Fedora-25.yaml
- data/Fedora-26.yaml
- data/Fedora-27.yaml
- data/PSBM.yaml
- data/RedHat-6.yaml
- data/common.yaml
- hiera.yaml
- manifests/init.pp
- manifests/repo.pp
- manifests/service.pp
- metadata.json
- spec/classes/lldpd_spec.rb
> Convert to data-in-modules

- metadata.json
We run unit tests on puppet5, so we know it works
> add support for puppet5

- .travis.yml
- spec/acceptance/lldpd_spec.rb
- spec/spec_helper_acceptance.rb
> Add acceptance tests

- manifests/repo.pp
> switch to https urls in the repofile

- .travis.yml
- data/CentOS-6.yaml
> add acceptance tests on centos6

- .fixtures.yml
- .travis.yml
- README.md
- data/Debian-8.yaml
- data/Debian-9.yaml
- data/Ubuntu-14.04.yaml
- data/Ubuntu-16.04.yaml
- manifests/repo.pp
- metadata.json
- spec/classes/lldpd_spec.rb
> add support for Debian8/9 and Ubuntu14.04/16.04

- data/Debian-8.yaml
- data/Debian-9.yaml
- data/Ubuntu-14.04.yaml
- data/Ubuntu-16.04.yaml
> fix scope typos in data

- .sync.yml
- .travis.yml
- spec/spec_helper.rb
> Modulesync 1.5.1

- README.md
> update documentation about CentOS

- data/RedHat-7.yml
- data/RedHat.yaml
- spec/classes/lldpd_spec.rb
> Add missing datafile for RedHat

- README.md
> add parameter section to README.md

- README.md
- data/common.yaml
- manifests/init.pp
- manifests/repo.pp
- manifests/service.pp
> switch to relative class scope / update gpg key for apt repos

- .sync.yml
- .travis.yml
> run acceptance tests on debian 9

- metadata.json
> bump puppet version requirement

- README.md
- metadata.json
- spec/classes/lldpd_spec.rb
I use this since months on FreeBSD 11 but somehow didn't document it
properly.
> fix documentation about FreeBSD 11 support

- .travis.yml
This is a test of https://github.com/voxpupuli/modulesync_config/pull/464
> execute travis jobs on newer ruby versions

- README.md
- data/Ubuntu-18.04.yaml
> add ubuntu 18.04 support

- .github/CONTRIBUTING.md
- .msync.yml
- Gemfile
> modulesync 1.9.1

- .msync.yml
- .sync.yml
- .travis.yml
- Gemfile
- metadata.json
- spec/classes/lldpd_spec.rb
> modulesync 1.9.3

- CHANGELOG.md
- metadata.json
> release 1.3.1

- .travis.yml
- data/Ubuntu-14.04.yaml
- metadata.json
> drop Ubuntu 14.04 support

- metadata.json
> allow puppetlabs/stdlib 6.x

- README.md
- data/VirtuozzoLinux-7.yaml
- metadata.json
> Add VirtuozzoLinux 7 support

- README.md
> fix docs links in README.md

- spec/classes/lldpd_spec.rb
> Update tests for VirtuozzoLinux 7

- CHANGELOG.md
- metadata.json
> release v2.1.0

- manifests/service.pp
> simplify systemd timer setup

- .sync.yml
- .travis.yml
- Gemfile
- README.md
- data/Debian-10.yaml
- data/Debian-8.yaml
- data/Debian-9.yaml
- data/Debian.yaml
- data/Ubuntu-16.04.yaml
> Add Debian 10 support

- metadata.json
This was forgotten in https://github.com/voxpupuli/puppet-lldpd/pull/84
> Add Debian10 to metadata.json

- REFERENCE.md
- data/Debian.yaml
- data/Fedora-28.yaml
- data/Fedora-29.yaml
- data/Fedora-30.yaml
- data/FreeBSD.yaml
- data/common.yaml
- manifests/init.pp
This allows us to generate a more useful REFERENCE.md and applies to our
best practices.
> move common.yaml to init.pp

- .github/SECURITY.md
- .msync.yml
- .rubocop.yml
- .travis.yml
- Gemfile
- manifests/init.pp
- manifests/install.pp
- manifests/repo.pp
- manifests/service.pp
- spec/spec_helper_acceptance.rb
> modulesync 3.0.0 & puppet-lint updates

- README.md
- data/Debian-8.yaml
- data/PSBM.yaml
- data/RedHat-6.yaml
- data/VirtuozzoLinux-6.yaml
- metadata.json
> Drop EoL CentOS 6

- README.md
- metadata.json
> Add FreeBSD 12 support

- metadata.json
this also contains https://github.com/voxpupuli/puppet-lldpd/pull/102
> Drop Puppet 5 support; enable Puppet 7 support

- metadata.json
> Allow latest dependencies

- .editorconfig
- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .gitignore
- .msync.yml
- .overcommit.yml
- .pmtignore
- .rspec
- .rspec_parallel
- .rubocop.yml
- .yardopts
- Dockerfile
- Gemfile
- REFERENCE.md
- Rakefile
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- spec/unit/facter/lldp_spec.rb
> modulesync 4.1.0

- CHANGELOG.md
- Rakefile
- metadata.json
> Release 3.0.1

- CHANGELOG.md
- Gemfile
- metadata.json
> release 3.0.2

- data/Gentoo.yaml
- metadata.json
> Enable Gentoo support

- .github/workflows/ci.yml
- .msync.yml
- Gemfile
- lib/facter/lldb.rb
- spec/acceptance/lldpd_spec.rb
- spec/classes/lldpd_spec.rb
- spec/spec_helper.rb
- spec/spec_helper_acceptance.rb
- spec/unit/facter/lldp_spec.rb
> modulesync 5.0.0

- data/Debian-10.yaml
- data/Debian.yaml
- metadata.json
> Add Debian 11 support

- data/Ubuntu-16.04.yaml
- data/Ubuntu-20.04.yaml
- data/Ubuntu.yaml
- spec/acceptance/lldpd_spec.rb
> Configure external repo for tests and cleanup hiera

- data/AlmaLinux.yaml
- data/Ubuntu-16.04.yaml
- data/Ubuntu-20.04.yaml
- data/Ubuntu.yaml
- metadata.json
- spec/acceptance/lldpd_spec.rb
> Add AlmaLinux support

- manifests/init.pp
This is suggested by upstream:
https://downloadcontent.opensuse.org/repositories/home:/vbernat/CentOS_7/home:vbernat.repo
> yumrepo: Set gpgcheck to 1

- data/Rocky.yaml
- metadata.json
Correct OS name:
```
$ puppet facts show os.name
{
"os.name": "Rocky"
}
```
> Add Rocky Linux support

- REFERENCE.md
- manifests/init.pp
- spec/setup_acceptance_node.pp
> apt: set gpg key checksum ensure=file

- lib/facter/lldp.rb
- spec/unit/facter/lldp_spec.rb
This fixes https://github.com/voxpupuli/puppet-lldpd/issues/129
> fact: Add support for single interfaces

- CHANGELOG.md
- metadata.json
> Release 4.0.2

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .msync.yml
- Dockerfile
- Gemfile
- README.md
- Rakefile
- data/Debian.yaml
- manifests/init.pp
- spec/spec_helper.rb
~~The key file used for debian-11 is different then the default one.~~
The previous apt key has expired and the key was replaced by a new one for which the checksum needs to be updated.
Fixes #140
> Update apt repository key checksums

- .github/CONTRIBUTING.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .msync.yml
- Dockerfile
- Gemfile
- README.md
- Rakefile
- data/Debian.yaml
- spec/spec_helper.rb
This was removed in #132 but a few bits slipped through.
While here remove the (outdated) in-line reference from REAME.md: we have
a REFERENCE.md file.
> Remove gpgkeyfingerprint leftovers

- metadata.json
> puppet/systemd: Allow 5.x & 6.x

- README.md
- metadata.json
Add Debian 12 and Ubuntu 24.04 (both tested already in production)
> Add Debian 12 and Ubuntu 24.04

- metadata.json
Bump APT constraint to include 10.x
> (metadata.json) Bump APT dependency to include 10.x
